name: Changed lines
description: Get all modified lines in a Pull Request
author: "Heston Hoffman"
branding:
  icon: 'git-pull-request'
  color: 'green'
inputs:
  token:
    description: 'Assign a GITHUB_TOKEN to use'
    required: false
    default: '${{ github.token }}'
  branch:
    description: 'Current PR branch'
    required: false
    default: '${{ github.ref_name }}'
  repo:
    description: 'Repository to compare against'
    required: false
    default: '${{ github.repository }}'
  pr:
    description: 'Pull Request number'
    required: false
    default: '${{ github.event.number }}'
  delimiter:
    description: 'Delimiter to use for changes_files output'
    required: false
    default: ' '
  file_filter:
    description: 'Filter for file extensions to include in output. Defaults to returning all file types'
    required: false
    default: ''
outputs:
  changed_lines:
    description: 'Lines with changes'
    value: '${{ steps.run_changed_lines.outputs.changed_lines }}'
  changed_files: 
    description: 'Files with changes'
    value: '${{ steps.run_changed_lines.outputs.changed_files }}'
runs:
  using: 'composite'
  steps:
    - run: |
        set -eu
        (
          cd "$ACTION_PATH"
          python3 -m venv venv
          venv/bin/pip install -r requirements.txt
        )
      shell: bash
      env:
        ACTION_PATH: '${{ github.action_path }}'
    - id: 'run_changed_lines'
      run: |
        set -eu
        exec "${ACTION_PATH}/venv/bin/python3" "$ACTION_PATH/main.py"
      shell: bash
      env:
        ACTION_PATH: '${{ github.action_path }}'
        # Cf. https://github.com/actions/runner/issues/665
        INPUT_TOKEN: '${{ inputs.token }}'
        INPUT_BRANCH: '${{ inputs.branch }}'
        INPUT_REPO: '${{ inputs.repo }}'
        INPUT_PR: '${{ inputs.pr }}'
        INPUT_DELIMITER: '${{ inputs.delimiter }}'
        INPUT_FILE_FILTER: '${{ inputs.file_filter }}'
